version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: prewave-tree
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
